[2022-05-21 12:41:16,362] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: backup_all_db.load_csv_to_new_db scheduled__2022-05-20T00:00:00+00:00 [queued]>
[2022-05-21 12:41:16,370] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: backup_all_db.load_csv_to_new_db scheduled__2022-05-20T00:00:00+00:00 [queued]>
[2022-05-21 12:41:16,371] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-21 12:41:16,371] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-21 12:41:16,371] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-21 12:41:16,388] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_csv_to_new_db> on 2022-05-20 00:00:00+00:00
[2022-05-21 12:41:16,393] {standard_task_runner.py:52} INFO - Started process 11414 to run task
[2022-05-21 12:41:16,398] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'backup_all_db', 'load_csv_to_new_db', 'scheduled__2022-05-20T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpc2hvx94f', '--error-file', '/tmp/tmpyngh6h1_']
[2022-05-21 12:41:16,399] {standard_task_runner.py:80} INFO - Job 5: Subtask load_csv_to_new_db
[2022-05-21 12:41:16,446] {task_command.py:369} INFO - Running <TaskInstance: backup_all_db.load_csv_to_new_db scheduled__2022-05-20T00:00:00+00:00 [running]> on host homerim-desktop
[2022-05-21 12:41:16,509] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=backup_all_db
AIRFLOW_CTX_TASK_ID=load_csv_to_new_db
AIRFLOW_CTX_EXECUTION_DATE=2022-05-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-20T00:00:00+00:00
[2022-05-21 12:41:16,510] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-21 12:41:16,511] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 ~/airflow/dags/tasks/load_csv_to_new_db.py']
[2022-05-21 12:41:16,519] {subprocess.py:85} INFO - Output:
[2022-05-21 12:41:16,832] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-21 12:41:16,832] {subprocess.py:92} INFO -   File "/home/home-rim/airflow/dags/tasks/load_csv_to_new_db.py", line 74, in <module>
[2022-05-21 12:41:16,832] {subprocess.py:92} INFO -     with open(f'/tmp/{table}.csv', 'r') as f:
[2022-05-21 12:41:16,832] {subprocess.py:92} INFO - FileNotFoundError: [Errno 2] No such file or directory: '/tmp/orders.csv'
[2022-05-21 12:41:16,857] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-21 12:41:16,872] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/home-rim/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 194, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-21 12:41:16,876] {taskinstance.py:1395} INFO - Marking task as UP_FOR_RETRY. dag_id=backup_all_db, task_id=load_csv_to_new_db, execution_date=20220520T000000, start_date=20220521T094116, end_date=20220521T094116
[2022-05-21 12:41:16,895] {standard_task_runner.py:92} ERROR - Failed to execute job 5 for task load_csv_to_new_db (Bash command failed. The command returned a non-zero exit code 1.; 11414)
[2022-05-21 12:41:16,933] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-21 12:41:16,959] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-21 13:06:14,949] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: backup_all_db.load_csv_to_new_db scheduled__2022-05-20T00:00:00+00:00 [queued]>
[2022-05-21 13:06:14,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: backup_all_db.load_csv_to_new_db scheduled__2022-05-20T00:00:00+00:00 [queued]>
[2022-05-21 13:06:14,959] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-21 13:06:14,959] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-21 13:06:14,959] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-21 13:06:14,977] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): load_csv_to_new_db> on 2022-05-20 00:00:00+00:00
[2022-05-21 13:06:14,983] {standard_task_runner.py:52} INFO - Started process 15631 to run task
[2022-05-21 13:06:14,991] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'backup_all_db', 'load_csv_to_new_db', 'scheduled__2022-05-20T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/my_first_dags.py', '--cfg-path', '/tmp/tmpmuhf7ihc', '--error-file', '/tmp/tmp82p0ezd8']
[2022-05-21 13:06:14,992] {standard_task_runner.py:80} INFO - Job 8: Subtask load_csv_to_new_db
[2022-05-21 13:06:15,046] {task_command.py:369} INFO - Running <TaskInstance: backup_all_db.load_csv_to_new_db scheduled__2022-05-20T00:00:00+00:00 [running]> on host homerim-desktop
[2022-05-21 13:06:15,106] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=backup_all_db
AIRFLOW_CTX_TASK_ID=load_csv_to_new_db
AIRFLOW_CTX_EXECUTION_DATE=2022-05-20T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-20T00:00:00+00:00
[2022-05-21 13:06:15,107] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-21 13:06:15,108] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 ~/airflow/dags/tasks/load_csv_to_new_db.py']
[2022-05-21 13:06:15,121] {subprocess.py:85} INFO - Output:
[2022-05-21 13:07:47,635] {subprocess.py:92} INFO - В новую базу загружен файл orders
[2022-05-21 13:07:47,635] {subprocess.py:92} INFO - В новую базу загружен файл supplier
[2022-05-21 13:07:47,635] {subprocess.py:92} INFO - В новую базу загружен файл nation
[2022-05-21 13:07:47,635] {subprocess.py:92} INFO - В новую базу загружен файл lineitem
[2022-05-21 13:07:47,635] {subprocess.py:92} INFO - В новую базу загружен файл region
[2022-05-21 13:07:47,635] {subprocess.py:92} INFO - В новую базу загружен файл customer
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В новую базу загружен файл partsupp
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В новую базу загружен файл part
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - Все данные успешно перенесены!
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице part находится 200000 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице partsupp находится 800000 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице lineitem находится 6001215 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице region находится 5 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице orders находится 1500000 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице nation находится 50 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице supplier находится 20000 записей
[2022-05-21 13:07:47,636] {subprocess.py:92} INFO - В таблице customer находится 150000 записей
[2022-05-21 13:07:47,643] {subprocess.py:96} INFO - Command exited with return code 0
[2022-05-21 13:07:47,689] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=backup_all_db, task_id=load_csv_to_new_db, execution_date=20220520T000000, start_date=20220521T100614, end_date=20220521T100747
[2022-05-21 13:07:47,745] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-05-21 13:07:47,765] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
